### ISSUE TITLE
Implement date tracking

### ISSUE THREAD

**Issue by kdbromley** [kdbromley/calenday-client#8]
- [ ] Today and selectedDate in state and context 
- [ ] Day view and Month view look for 'selectedDate', else Today on load
- [ ] Update getDatesArray to current month so dropdown is quick select based on today
